#!/usr/bin/env sh

CCF=gcc
CFLAGS='-O2 -Os'
OP='ccc'

#compile

if [[ $1 == '-e' ]]; then
	$CCF $CFLAGS ccc-extended.c -o ccc
else
	$CCF $CFLAGS ccc.c -o ccc
fi

if [[ $2 == '-i' ]]; then
	mv $OP ~/bin/
fi
